enum OrderState {
  RECIBIDO = 'RECIBIDO',
  EN_PROCESO = 'EN_PROCESO',
  SIN_STOCK = 'SIN_STOCK',
  CANCELADO = 'CANCELADO',
  RECHAZADO = 'RECHAZADO',
  EN_DISTRIBUCION = 'EN_DISTRIBUCION',
  ENTREGADO = 'ENTREGADO'
}

export default OrderState;